version: "3"

services:
  db:
    container_name: docker-view-mysql
    image: mysql:8
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=docker_views
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"